### ISSUE TITLE
Local planner - drifts when moving towards local target

### ISSUE THREAD

**Issue by IsaacHook** [ursa-drone/ursa-server#10]
https://github.com/ursa-drone/ursa-server/tree/23502da7f3af901f6f71a7c37d7a80000317b7ed
- Heading does not correct to current local plan heading.  Just moves in the correct direction
- May be because local plan is updating too fast for px4 control.  Update cost function to favour previous trajectories.
![screenshot from 2017-07-30 12-13-26](https://user-images.githubusercontent.com/12621911/28750075-7ef59652-7521-11e7-8d43-9b94db17da23.png)

**Comment by IsaacHook** [comment]
> Update cost function to favour previous trajectories.
- Does not help drifting.
![screenshot from 2017-07-30 17-12-30](https://user-images.githubusercontent.com/12621911/28751417-5c3748a8-754a-11e7-88c5-ff3a876a633b.png)

**Comment by IsaacHook** [comment]
- Issue only occurs on home computer (not on lab computers)

**Comment by lachyd** [comment]
Could not replicate.
