### ISSUE TITLE
Local Planner - overshoots goal

### ISSUE THREAD

**Issue by IsaacHook** [ursa-drone/ursa-server#13]
- Does not slow down before goal.  Overshoots and then corrects.
![screenshot from 2017-07-31 14-22-34](https://user-images.githubusercontent.com/12621911/28762692-d424e9ea-75fb-11e7-9438-8bdf56189f8a.png)

**Comment by IsaacHook** [comment]
- when goal is set close to walls, drifting behaviour could lead to collisions
![screenshot from 2017-07-31 14-35-55](https://user-images.githubusercontent.com/12621911/28762928-9eafae7e-75fd-11e7-8576-019d23a93bf8.png)

**Comment by lachyd** [comment]
Done - overshoot is limited by max XY velocity in PX4.
