### ISSUE TITLE
Local planner - unstable behaviour when goal is in costmap

### ISSUE THREAD

**Issue by IsaacHook** [ursa-drone/ursa-server#15]
- global planner fails to get plan as goal is in costmap.
- local planner oscillates depending on cost functions.
![screenshot from 2017-07-31 14-28-57](https://user-images.githubusercontent.com/12621911/28762815-c7f3cd8e-75fc-11e7-83a3-7a1847743125.png)

**Comment by lachyd** [comment]
Recovery behaviours are now implemented, will now gracefully fail in this case.
