### ISSUE TITLE
Unstable behaviour when close to reaching goal

### ISSUE THREAD

**Issue by IsaacHook** [ursa-drone/ursa-server#2]

**Comment by IsaacHook** [comment]
![screenshot from 2017-07-26 12-54-49](https://user-images.githubusercontent.com/12621911/28602476-a841215c-7201-11e7-9f96-a61266c173e4.png)

**Comment by lachyd** [comment]
Solved by overriding local planner in simulation.py...
May be more robust to set local plan orientation to match global plan when within robot footprint.
![screenshot from 2017-07-28 13-34-34](https://user-images.githubusercontent.com/10256694/28701423-865ba168-7399-11e7-9c29-588934191d00.png)

**Comment by IsaacHook** [comment]
Solved by overriding local planner in simulation.py...
May be more robust to set local plan orientation to match global plan when within robot footprint.
![screenshot from 2017-07-28 13-34-34](https://user-images.githubusercontent.com/10256694/28701423-865ba168-7399-11e7-9c29-588934191d00.png)
