### ISSUE TITLE
Local planner - gets stuck when local trajectories > 45 degrees

### ISSUE THREAD

**Issue by IsaacHook** [ursa-drone/ursa-server#21]
- happens because tries to rotate when 45 degrees from global plan
- local trajectories are being generated > 45 degrees from global plan

![screenshot from 2017-08-09 19-10-28](https://user-images.githubusercontent.com/12621911/29114175-c6e639cc-7d36-11e7-9d5c-c8f8dac940c8.png)

**Comment by lachyd** [comment]
Fixed.
